"""Core data structures for the Orbital Edge Computing model.

The implementation keeps the physical meaning of every edge explicit.  A state
node identifies a physical node, a time cycle and the processing state of the
service, while edges represent transmission, storage or processing operations.
This separation is useful later because the QUBO formulation associates binary
variables only with physically admissible transitions.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Sequence


@dataclass(frozen=True, order=True)
class StateNode:
    """A physical node at one time cycle and processing state."""

    physical: str
    time: int
    processed: int

    def __post_init__(self) -> None:
        if self.time < 0:
            raise ValueError("time must be non-negative")
        if self.processed not in (0, 1):
            raise ValueError("processed must be either 0 or 1")


@dataclass(frozen=True)
class Service:
    """Earth-observation service generated by one satellite."""

    name: str
    source: str
    generation_time: int
    deadline: int
    unprocessed_mb: float
    processed_mb: float

    def __post_init__(self) -> None:
        if self.deadline < self.generation_time:
            raise ValueError("deadline must not precede generation_time")
        if self.unprocessed_mb <= 0 or self.processed_mb <= 0:
            raise ValueError("service sizes must be positive")
        if self.processed_mb > self.unprocessed_mb:
            raise ValueError("processed size must not exceed unprocessed size")

    def size_for_state(self, processed: int) -> float:
        """Return the amount of data carried in the requested processing state."""
        if processed == 0:
            return self.unprocessed_mb
        if processed == 1:
            return self.processed_mb
        raise ValueError("processed must be either 0 or 1")


@dataclass(frozen=True)
class Edge:
    """One admissible transition of the time-expanded OEC graph."""

    name: str
    source: StateNode
    target: StateNode
    kind: str
    resource_key: str
    unit_energy_j_per_mb: float = 0.0

    def __post_init__(self) -> None:
        if self.kind not in {"transmission", "storage", "processing"}:
            raise ValueError(f"unsupported edge kind: {self.kind}")
        if self.unit_energy_j_per_mb < 0:
            raise ValueError("unit energy must be non-negative")

        if self.kind == "processing":
            if self.source.physical != self.target.physical:
                raise ValueError("processing cannot change physical node")
            if self.source.time != self.target.time:
                raise ValueError("processing occurs within one time cycle")
            if (self.source.processed, self.target.processed) != (0, 1):
                raise ValueError("processing must change state from 0 to 1")

        if self.kind == "storage":
            if self.source.physical != self.target.physical:
                raise ValueError("storage cannot change physical node")
            if self.source.processed != self.target.processed:
                raise ValueError("storage cannot change processing state")
            if self.target.time != self.source.time + 1:
                raise ValueError("storage must advance exactly one time cycle")

        if self.kind == "transmission":
            if self.source.physical == self.target.physical:
                raise ValueError("transmission must change physical node")
            if self.source.time != self.target.time:
                raise ValueError("transmission occurs within one time cycle")
            if self.source.processed != self.target.processed:
                raise ValueError("transmission cannot change processing state")


@dataclass(frozen=True)
class OECInstance:
    """Complete deterministic OEC optimization instance."""

    name: str
    ground_node: str
    services: Sequence[Service]
    edges: Sequence[Edge]
    resource_capacities_mb: Mapping[str, float]
    energy_budgets_j: Mapping[tuple[str, int], float]

    def __post_init__(self) -> None:
        edge_names = [edge.name for edge in self.edges]
        if len(edge_names) != len(set(edge_names)):
            raise ValueError("edge names must be unique")

        service_names = [service.name for service in self.services]
        if len(service_names) != len(set(service_names)):
            raise ValueError("service names must be unique")

        for edge in self.edges:
            if edge.resource_key not in self.resource_capacities_mb:
                raise ValueError(
                    f"missing capacity for resource {edge.resource_key!r}"
                )

    @property
    def nodes(self) -> tuple[StateNode, ...]:
        """Return all state nodes that occur in the graph."""
        return tuple(
            sorted(
                {edge.source for edge in self.edges}
                | {edge.target for edge in self.edges}
            )
        )

    def source_node(self, service: Service) -> StateNode:
        return StateNode(service.source, service.generation_time, 0)

    def sink_node(self, service: Service) -> StateNode:
        return StateNode(self.ground_node, service.deadline, 1)

    def edge_data_mb(self, service: Service, edge: Edge) -> float:
        """Data amount consuming the capacity associated with an edge.

        Transmission and storage carry data in the processing state of the edge.
        Processing consumes the unprocessed service size, consistently with the
        processing-capacity definition of the reference OEC model.
        """
        if edge.kind == "processing":
            return service.unprocessed_mb
        return service.size_for_state(edge.source.processed)

    def ground_processing_cost(self, service: Service, edge: Edge) -> float:
        """Ground-processing contribution of one selected edge."""
        if (
            edge.kind == "processing"
            and edge.source.physical == self.ground_node
        ):
            return service.unprocessed_mb * edge.unit_energy_j_per_mb
        return 0.0

    def onboard_energy(self, service: Service, edge: Edge) -> float:
        """Energy charged to the sending/processing satellite for one edge."""
        if edge.source.physical == self.ground_node:
            return 0.0
        return self.edge_data_mb(service, edge) * edge.unit_energy_j_per_mb
